# KBDS to DDBJ 변환 도구 설정 파일 (최신 경로 반영)

# 제출 데이터(우리가 제출한 원본)
input_xml_dir: /home/drake/work_local/XMLmeta/xml_submitted
# 실제 DDBJ 예시 데이터(실제 제출본)
real_examples_dir: /home/drake/work_local/XMLmeta/real_examples
# 제출 데이터에 대한 피드백 코멘트가 포함된 데이터(주석 포함 샘플)
reviewed_xml_dir: /home/drake/work_local/XMLmeta/xml_reviewed

output_xml_dir: ./output_xml
log_dir: ./logs
xsd_base_dir: ./pub/docs

# 각 메타데이터 유형별 XSD 경로 (pub/docs 하위)
xsd_paths:
  bioproject: bioproject/xsd/Package.xsd
  biosample: biosample/xsd/biosample_set.xsd
  experiment: dra/xsd/1-6/SRA.experiment.xsd
  run: dra/xsd/1-6/SRA.run.xsd
  submission: dra/xsd/1-6/SRA.submission.xsd

# 기타 옵션
log_level: INFO
feedback_dir: ./feedback
